language: php

php:
  - 5.6
  - 7.3

before_install:
  - cd ${TRAVIS_BUILD_DIR}

install:
  - composer install

script:
  # PHPCS prints loads of warnings for undefined visibility for constants.
  # Ignore those until we really want to drop PHP <= 7.1 compatibility.
  - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --ignore='vendor/*' --standard=PSR12 --exclude=Generic.Files.LineLength .
  - vendor/bin/phpunit tests
